Update PE_Exercise_1.py
tshiu/PETraining pull request #10
Opened 2018-03-27 03:44 UTC by tshiu

Added while loop

2018-03-28 01:42 UTC, tshiu commented
@mlezeng I think I accidentally deleted the PE Exercises from my master branch and now have conflicts to be resolved. Not quite sure how do these, would love to go over this. Otherwise, the exercises and deliverables should be present!

2018-03-29 23:55 UTC, mlezeng requested changes

2018-03-29 23:55 UTC, mlezeng commented on PE_Exercise_1.py
> +path = /v2.0/{record_type}
Can you update this to match Python's format for adding variables?

2018-03-29 23:55 UTC, mlezeng commented on PE_Exercise_1.py
> +client_ID = [Client_ID_for_district]
for district or app?

Also, you may need to query for this data.

2018-03-29 23:55 UTC, mlezeng commented on ex33.py
> +	while i < 6:
The 6 in this line should have been replaced by a variable per the study drill

2018-03-29 23:55 UTC, mlezeng commented on ex33.py
> +	while i < 6:
This doesn't have to be fixed since I see you did this below

2018-03-29 23:55 UTC, mlezeng commented on ex35.py
> +	# If the string in next contains either 1 or 0, we will set the variable how_much
I think you described what the original function did, then updated the function to improve it. Can you update your comment to show what the new function does?

2018-03-29 23:55 UTC, mlezeng commented on ex36.py
> +		elif next == "throw" and not wig_fallen:
Is there a case where wig_fallen would be set to true? If so, where? If not, why include this?

2018-03-29 23:55 UTC, mlezeng commented on m9del.py
> +	if new_guess == guess:
Hmm....if the user keeps entering the same number each time, guess should not go up. Can you rewrite this the reflect that?

Hint: maybe there should be another loop here!

2018-03-29 23:55 UTC, mlezeng commented on m9del.py
> +else:
Does this run? Since this else line is tabbed back to start, it's not considered part of the loop. I think this line shouldn't be here?

2018-03-30 22:29 UTC, tshiu commented on ex36.py
> +		elif next == "throw" and not wig_fallen:
Oops, I think I was thinking of making things more complicated but then forgot about it. I removed the wig_fallen variable

2018-03-30 22:30 UTC, tshiu commented on m9del.py
> +	if new_guess == guess:
added a while loop instead!

2018-03-30 22:30 UTC, tshiu commented on m9del.py
> +else:
adjusted the tab

2018-03-30 22:30 UTC, tshiu commented on ex35.py
> +	# If the string in next contains either 1 or 0, we will set the variable how_much
Updated!

2018-03-30 22:38 UTC, tshiu commented on PE_Exercise_1.py
> +path = /v2.0/{record_type}
Done, I believe

2018-03-30 22:39 UTC, tshiu commented on ex33.py
> +	while i < 6:
Oops, adjusted

2018-03-30 22:40 UTC, tshiu commented on PE_Exercise_1.py
> +client_ID = [Client_ID_for_district]
App! yes, I wasn't quite sure how to query for it but will make a note to add this as we go along

2018-03-30 22:47 UTC, tshiu commented
@mlezeng  I believe I made the changes. let me know!

2018-04-26 00:26 UTC, mlezeng approved these changes

2018-05-08 17:29 UTC, closed without merging