Milestone 8
tshiu/PETraining pull request #9
Opened 2018-03-22 21:38 UTC by tshiu

Milestone 8 Exercises

2018-03-23 22:29 UTC, mlezeng requested changes

2018-03-23 22:29 UTC, mlezeng commented on PE_Exercise_1.py
> +def get_tokens(district):
Why does this function take in district as an input?

2018-03-23 22:29 UTC, mlezeng commented on PE_Exercise_1.py
> +get_tokens
Are you calling the get_tokens function? If so, you are missing the (district) values

2018-03-23 22:29 UTC, mlezeng commented on PE_Exercise_1.py
> +total_users
I'm not 100% here, but I believe that this might cause an error if the call for total users (which is missing (record_type,district) comes before the function total_users is defined

2018-03-23 22:29 UTC, mlezeng commented on PE_Exercise_1.py
> +	def page_through():
Careful here! Since def is tabbed one over, this isn't defining the function in the way that you expect; rather, this is being trated as part of total_users. Make sure you un-tab this section!

2018-03-23 22:29 UTC, mlezeng commented on PE_Exercise_2.py
> +		If student.schools.len > 1,
Why is this tabbed over?

2018-03-23 22:29 UTC, mlezeng commented on PE_Exercise_2.py
> +		def page_through():
Why is this tabbed over?

2018-03-23 22:41 UTC, tshiu commented
@mlezeng I believe I made the corrections! Let me know if you need anything else.

2018-03-26 20:28 UTC, mlezeng approved these changes
Almost there! But these are OK - make sure you're keeping track of those tabs, tho

2018-03-26 20:28 UTC, mlezeng commented on PE_Exercise_2.py
> +   	GET tokens at https://clever.com/oauth/tokens?owner_type=district
This line ended up getting tabbed over

2018-03-26 20:28 UTC, mlezeng commented on PE_Exercise_2.py
> +    	return token
This one too

2018-03-28 01:36 UTC, merged